{% set name = "panoptica" %}
{% set version = "1.4.1" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/panoptica-{{ version }}.tar.gz
  sha256: 9eb3a2824ae0408b2510ddf4b3493b3dbeabd3df9bfeaa5ce4504d36e8b1519a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - poetry-dynamic-versioning >=1.0.0,<2.0.0
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.20.0,<2.0.0
    - connected-components-3d >=3.12.3,<4.0.0
    - scipy >=1.7.0,<2.0.0
    - rich >=13.6.0,<14.0.0
    - scikit-image >=0.22.0,<0.23.0
    - simpleitk >=2.2.2
    - ruamel.yaml >=0.18.6,<0.19.0
    - plotly >=5.16.1,<6.0.0
    - pandas >=2.1.0,<3.0.0
    - joblib >=1.3.2,<2.0.0
    - tqdm >=4.62.3
    - typer >=0.15.0
    - pytorch >=2.1.0
    - nibabel >=5.1.0

test:
  imports:
    - panoptica
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  summary: Panoptic Quality (PQ) computation for binary masks.
  home: https://github.com/BrainLesion/panoptica
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sarthakpati
